# How Many Displates Do You Need To Order?
Displates: 3

# Paste the links here:
displate1: https://displate.com/displate/892142
displate2: https://displate.com/displate/892142
displate3: https://displate.com/displate/892142
displate4:
displate5:
displate6:
displate7:
displate8:
displate9:
displate10:

# What's the size of each displate? Abbreviated (ex. "m", "l", "xl")
size1: l
size2: l
size3: l
size4: 
size5: 
size6: 
size7: 
size8: 
size9: 
size10: 

# Is the displate's finish gloss?
finish1: "no"
finish2: "no"
finish3: "no"
finish4: "no"
finish5: "no"
finish6: "no"
finish7: "no"
finish8: "no"
finish9: "no"
finish10: "no"

# Email of recipient
Email: marit.koeffers@web.de

# Phone number (keep inside double quotes)
Phone: "4915782292010"

# Full name
Name: Marit Köffers

# Address Line 1
Address1: Poststraße 35

# Address Line 2 (Leave blank if needed)
Address2:

# City
City: Ratingen

# State (Abbreviated)
State: 

# Zip Code (keep inside double quotes)
Postal: "40878"